In [3]:
import numpy as np


np_a = np.array([
    [10, 20, 30, 40], 
    [5, 15, 25, 35],  
    [12, 22, 32, 42]  
])

In [5]:
transp = np_a.T

In [7]:

print("Original array :")
print(np_a)

print("\nTransposed array:")
print(transp)

Original array :
[[10 20 30 40]
 [ 5 15 25 35]
 [12 22 32 42]]

Transposed array:
[[10  5 12]
 [20 15 22]
 [30 25 32]
 [40 35 42]]
