In [3]:
import numpy as np

arr = np.random.randint(1, 21, size=(3, 4))
print("Original :")
print(arr)

Original :
[[ 8 14 10  8]
 [17  1 10 20]
 [ 2 15 12 10]]


In [5]:
res_ar = arr.reshape(2, 6)
print("\nReshaped to 2x6:")
print(res_ar)


Reshaped to 2x6:
[[ 8 14 10  8 17  1]
 [10 20  2 15 12 10]]


In [7]:
trans_a = res_ar.T
print("\nTransposed (6x2:")
print(trans_a)


Transposed (6x2:
[[ 8 10]
 [14 20]
 [10  2]
 [ 8 15]
 [17 12]
 [ 1 10]]
